### PR TITLE
made OK, WithStatus and NotFound on stub to return IRequestVerify

### PR DESCRIPTION
**Pull request by kesot**

### CODE REVIEW

**Comment by hibri** [comment]
Thanks for this @kesot :)
Could you write a test(s) for this? It makes sure the functionality is not broken in future, and also it would be good to use the test as an example on how to use the functionality.

**Comment by kesot** [comment]
Ok... Will do

**Comment by hibri** [comment]
Hi @kesot,
Looking at the tests, I can't see a use case for this change. 
Can you explain a bit more what you are trying to do?

IRequestVerify is an interface that is used with AssertWasCalled, and to verify how requests are made.
IRequestStub is used to setup how the mock responds, and the interface strictly caters to that.
It will be confusing to a user of a fluent interface if things that are not related are returned.

**Comment by kesot** [comment]
Well, when I setup mock I expect to have an object at the end of the fluent interface which I can use for assertion.
How do you assert now headers or body of request sent to the handler?

**Comment by hibri** [comment]
You can assert using the AssertWasCalled  extensions. 
See https://github.com/hibri/HttpMock/blob/master/src/HttpMock.Integration.Tests/HttpExpectationTests.cs  for some examples.

**Comment by kesot** [comment]
It's not shipped with nuget package

**Comment by kesot** [comment]
Oh, I see the problem now, I was not able to find any verification methods because they are separated to the different package. But why?

**Comment by hibri** [comment]
Didn't want to ship a NUnit dependency with the main project, and if you are using your own testing framework it's easier to extend it.

**Comment by kesot** [comment]
And why do I have to depend on NUnit if I use HttpMock in MSTests for example?

**Comment by hibri** [comment]
You are free to use MSTest, but if you use MSTest, you can write your own extensions, using the example in the HttpMock.Verify.NUnit library. I'd like to keep the verification concerns separate from the main library.

**Pull request closed without merging**
